---
deployment:
  tasks:
    - export DEPLOYPATH=/home/coolappl/hangoutio.com
    - /bin/cp -R * $DEPLOYPATH
    - /usr/bin/rsync -av --delete $HOME/repositories/hangoutio-staging/ $HOME/hangoutio.com/
